#include "aether/project/project.h"

#include "aether/core/log.h"
#include "aether/platform/filesystem.h"
#include "aether/reflection/serialize.h"

#include <cstdio>
#include <system_error>

namespace aether {

namespace {

namespace stdfs = std::filesystem;

void SetError(std::string* error, std::string message) {
    if (error != nullptr) {
        *error = std::move(message);
    }
}

bool IsValidProjectName(const std::string& name) {
    if (name.empty() || name.size() > 64 || name == "." || name == "..") {
        return false;
    }
    for (char c : name) {
        const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' ||
                        c == '-' || c == ' ';
        if (!ok) {
            return false;
        }
    }
    return name.front() != ' ' && name.back() != ' ';
}

// "0.7.2" -> {0, 7}; false if it doesn't start with two dot-separated numbers.
bool ParseMajorMinor(const std::string& version, int& major, int& minor) {
    return std::sscanf(version.c_str(), "%d.%d", &major, &minor) == 2;
}

constexpr const char* kGitIgnore =
    "# Generated by the Aether editor: regenerated on demand, never committed.\n"
    "Saved/\n"
    "Intermediate/\n";

} // namespace

std::vector<QualityPreset> DefaultQualityPresets() {
    // name, resolution scale, shadow texels, cascades, view distance, MSAA, bloom
    return {
        {"Low", 0.75f, 1024, 2, 300.0f, 1, false},
        {"Medium", 1.0f, 1024, 3, 600.0f, 1, true},
        {"High", 1.0f, 2048, 4, 1000.0f, 2, true},
        {"Epic", 1.0f, 4096, 4, 2500.0f, 4, true},
    };
}

const QualityPreset* FindQualityPreset(const ProjectSettings& settings, const std::string& name) {
    for (const QualityPreset& p : settings.quality_presets) {
        if (p.name == name) return &p;
    }
    return nullptr;
}

ProjectPaths ProjectPaths::ForFile(const stdfs::path& project_file) {
    ProjectPaths paths;
    paths.file = project_file;
    paths.root = project_file.parent_path();
    paths.content = paths.root / "Content";
    paths.config = paths.root / "Config";
    paths.source = paths.root / "Source";
    paths.saved = paths.root / "Saved";
    paths.intermediate = paths.root / "Intermediate";
    return paths;
}

bool EnsureProjectFolders(const ProjectPaths& paths, std::string* error) {
    for (const stdfs::path& dir : {paths.content, paths.config, paths.saved, paths.intermediate}) {
        std::error_code ec;
        stdfs::create_directories(dir, ec);
        if (ec) {
            SetError(error, "Couldn't create " + dir.string() + ": " + ec.message());
            return false;
        }
    }
    return true;
}

bool CreateProject(const stdfs::path& parent_dir, const std::string& name, ProjectPaths* out_paths,
                   std::string* error) {
    if (!IsValidProjectName(name)) {
        SetError(error, "\"" + name + "\" isn't a valid project name: use letters, digits, spaces, '-' and '_' "
                        "(1-64 characters, not starting or ending with a space)");
        return false;
    }
    const stdfs::path root = parent_dir / name;
    std::error_code ec;
    if (stdfs::exists(root, ec) && !stdfs::is_empty(root, ec)) {
        SetError(error, root.string() + " already exists and isn't empty");
        return false;
    }

    ProjectPaths paths = ProjectPaths::ForFile(root / (name + kProjectExtension));
    if (!EnsureProjectFolders(paths, error)) {
        return false;
    }
    const std::string gitignore(kGitIgnore);
    if (!fs::WriteFileBytes((root / ".gitignore").string(), gitignore.data(), gitignore.size())) {
        SetError(error, "Couldn't write " + (root / ".gitignore").string());
        return false;
    }

    ProjectSettings settings;
    settings.name = name;
    if (!SaveProject(paths.file, settings, error)) {
        return false;
    }
    if (out_paths != nullptr) {
        *out_paths = paths;
    }
    return true;
}

bool SaveProject(const stdfs::path& project_file, const ProjectSettings& settings, std::string* error) {
    ProjectSettings stamped = settings;
    stamped.engine_version = kEngineVersion;
    reflect::Json json = reflect::ToJson(stamped);
    json["$type"] = "Project";
    std::string text = json.dump(2);
    text.push_back('\n');
    if (!fs::WriteFileBytes(project_file.string(), text.data(), text.size())) {
        SetError(error, "Couldn't write " + project_file.string());
        return false;
    }
    return true;
}

bool LoadProject(const stdfs::path& project_file, ProjectSettings& out, std::string* error,
                 std::vector<std::string>* warnings) {
    std::vector<u8> bytes;
    if (!fs::ReadFileBytes(project_file.string(), bytes)) {
        SetError(error, "Couldn't read " + project_file.string());
        return false;
    }
    reflect::Json json = reflect::Json::parse(bytes.begin(), bytes.end(), nullptr, /*allow_exceptions=*/false);
    if (json.is_discarded() || !json.is_object() || json.value("$type", "") != "Project") {
        SetError(error, project_file.string() + " isn't an Aether project file");
        return false;
    }

    ProjectSettings settings;
    reflect::LoadReport report;
    if (!reflect::FromJson(settings, json, &report)) {
        SetError(error, project_file.string() + " couldn't be read as project settings");
        return false;
    }
    int major = 0, minor = 0;
    if (ParseMajorMinor(settings.engine_version, major, minor) &&
        (major > kEngineVersionMajor || (major == kEngineVersionMajor && minor > kEngineVersionMinor))) {
        report.warnings.push_back("The project was saved by a newer engine (" + settings.engine_version + ", this is " +
                                  kEngineVersion + "); settings it added are ignored");
    }
    if (settings.layers.empty() || settings.layers.front() != "Default") {
        settings.layers.insert(settings.layers.begin(), "Default");
        report.warnings.push_back("Collision layer 0 must be \"Default\"; added it");
    }
    if (settings.layers.size() > 32) {
        settings.layers.resize(32);
        report.warnings.push_back("More than 32 collision layers; the extra ones were dropped");
    }

    for (std::string& warning : report.warnings) {
        if (warnings != nullptr) {
            warnings->push_back(std::move(warning));
        } else {
            AETHER_LOG_WARN("Project", "%s", warning.c_str());
        }
    }
    out = std::move(settings);
    return true;
}

} // namespace aether
